version: '3'
services:
    mssql:
        container_name: mssql
        image: 'mcr.microsoft.com/mssql/server'
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Abcd#1234
        #volumes:
        #    - './drive:/var/opt/mssql'
